name: Kafka Producer Limited Deployment

on:
  push:  
    branches:
      - main

  workflow_dispatch: 

  schedule:
    - cron: "0 10,14,18 * * 1-5"  # Runs at 10 AM, 2 PM, 6 PM (Mon-Fri)

jobs:
  run-producer:
    runs-on: ubuntu-latest

    permissions:
      actions: write  # must have repo write access to trigger

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.11"

    - name: Install Kafka from GitHub Releases & Start Services
      run: |
        # Define Kafka version & download URL from GitHub Releases
        KAFKA_VERSION=3.5.1
        KAFKA_SCALA_VERSION=2.13
        KAFKA_DIR=/tmp/kafka
        KAFKA_TGZ="/tmp/kafka_$KAFKA_SCALA_VERSION-$KAFKA_VERSION.tgz"
        GITHUB_RELEASE_URL="https://github.com/yourusername/yourrepo/releases/download/v1.0/kafka_$KAFKA_SCALA_VERSION-$KAFKA_VERSION.tgz"

        # Download Kafka from GitHub Releases
        echo "Downloading Kafka from GitHub Releases..."
        curl -fsSL -o "$KAFKA_TGZ" "$GITHUB_RELEASE_URL"

        # Verify download was successful
        if [[ ! -s "$KAFKA_TGZ" ]]; then
          echo "ERROR: Kafka download failed. Exiting..."
          exit 1
        fi

        # Extract Kafka
        tar -xzf "$KAFKA_TGZ" -C /tmp || { echo "ERROR: Failed to extract Kafka. Exiting..."; exit 1; }
        mv "/tmp/kafka_$KAFKA_SCALA_VERSION-$KAFKA_VERSION" "$KAFKA_DIR"

        # Start Zookeeper
        nohup "$KAFKA_DIR/bin/zookeeper-server-start.sh" "$KAFKA_DIR/config/zookeeper.properties" > zookeeper.log 2>&1 &
        sleep 15  # Wait for Zookeeper to start

        # Start Kafka
        nohup "$KAFKA_DIR/bin/kafka-server-start.sh" "$KAFKA_DIR/config/server.properties" > kafka.log 2>&1 &
        sleep 15  # Wait for Kafka to start

        # Log Zookeeper & Kafka Status
        echo "---- Zookeeper Logs ----"
        tail -n 20 zookeeper.log
        echo "---- Kafka Logs ----"
        tail -n 20 kafka.log


    - name: Install dependencies
      run: |
        python3 -m venv .venv
        source .venv/bin/activate
        python3 -m pip install --upgrade pip setuptools wheel
        python3 -m pip install -r requirements.txt
        python3 -m pip list  

    - name: Run Kafka Producer (Limited to 20 Minutes)
      run: |
        source .venv/bin/activate
        export PYTHONPATH="$PYTHONPATH:$(pwd)"  # local imports
        timeout 20m python3 producers/producer_earthquake.py  
