name: Kafka Producer and Consumer (Limited) Deployment

on:
  push:
    branches:
      - main
  workflow_dispatch:
  schedule:
    - cron: "0 10,14,18 * * 1-5"  # Runs at 10 AM, 2 PM, 6 PM (Mon-Fri)

jobs:
  kafka-test:
    runs-on: ubuntu-latest

    services:
      zookeeper:
        image: wurstmeister/zookeeper:latest
        ports:
          - 2181:2181

      kafka:
        image: wurstmeister/kafka:latest
        ports:
          - 9092:9092
        env:
          KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
          KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
          KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
          KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.11"

    - name: Install dependencies
      run: |
        python3 -m venv .venv
        source .venv/bin/activate
        python3 -m pip install --upgrade pip setuptools wheel
        python3 -m pip install --upgrade -r requirements.txt
        python3 -m pip list  

    - name: Wait for Kafka to be Ready
      run: |
        echo "Waiting for Kafka to be ready..."
        sleep 30  # Allow some time for Kafka to fully start

    - name: Run Kafka Producer (Limited to 20 Minutes)
      run: |
        source .venv/bin/activate
        export PYTHONPATH="$PYTHONPATH:$(pwd)"  # Local imports
        timeout 20m python3 producers/producer_earthquake.py

    - name: Run Kafka Consumer (Limited to 20 Minutes)
      run: |
        source .venv/bin/activate
        export PYTHONPATH="$PYTHONPATH:$(pwd)"  # Local imports
        timeout 20m python3 consumers/consumer_earthquake.py
