name: Kafka Producer Limited Deployment

on:
  push:  
    branches:
      - main

  workflow_dispatch: 

  schedule:
    - cron: "0 10,14,18 * * 1-5"  # Runs at 10 AM, 2 PM, 6 PM (Mon-Fri)

jobs:
  run-producer:
    runs-on: ubuntu-latest

    permissions:
      actions: write  # must have repo write access to trigger

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.11"

    - name: Install dependencies
      run: |
        python3 -3.11 -m venv .venv
        source .venv/bin/activate
        python3 -m pip install --upgrade pip setuptools wheel
        python3 -m pip install -r requirements.txt
        python3 -m pip list  

    - name: Run Kafka Producer (Limited to 20 Minutes)
      run: |
        source .venv/bin/activate
        export PYTHONPATH="$PYTHONPATH:$(pwd)"  # local imports
        timeout 20m python3 producers/producer_earthquake.py  
