name: Kafka Producer Limited Deployment

on:
  push:  
    branches:
      - main

  workflow_dispatch: # Allows manual trigger (restricted)

  schedule:
    - cron: "0 10,14,18 * * 1-5"  # Runs at 10 AM, 2 PM, 6 PM (Mon-Fri)

jobs:
  run-producer:
    runs-on: ubuntu-latest

    permissions:
      actions: write  # Restrict manual triggers to repo maintainers

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.11"

    - name: Install dependencies
      run: |
        python -m venv .venv
        source .venv/bin/activate
        pip install -r requirements.txt

    - name: Run Kafka Producer (Limited to 20 Minutes)
      run: |
        timeout 20m python producers/producer_earthquake.py  # Stop after 20 min
